# Generated by Django 4.2.11 on 2024-02-04 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invest', '0002_about_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(choices=[('Select Coin', 'Select Coin'), ('Bitcoin', 'Bitcoin'), ('Ethurum', 'Ethurum'), ('BnB', 'BnB'), ('USDT Tron', 'USDT Tron'), ('USDT Tron', 'USDT ERC20')], default='Select Coin', max_length=100)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Rewarded', 'Rewarded')], default='Pending', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
